import { ArrowLeft, Save, Star } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../../services/api';
import { ErrorBox, LoadingAdmin, SuccessBox } from '../components/AdminFeedback';
import SerperImagePicker from '../components/SerperImagePicker';

const initial = { name:'', brand:'', categoryId:'', price:'', stock:'', image:'', description:'', featured:false };

function CadastroProduto() {
  const {id}=useParams(); const editando=Boolean(id); const navigate=useNavigate(); const [form,setForm]=useState(initial); const [categorias,setCategorias]=useState([]); const [loading,setLoading]=useState(editando); const [saving,setSaving]=useState(false); const [erro,setErro]=useState(''); const [sucesso,setSucesso]=useState('');
  useEffect(()=>{let active=true;async function load(){try{const categoryReq=api.get('/categories');const productReq=editando?api.get(`/products/${id}`):Promise.resolve(null);const[c,p]=await Promise.all([categoryReq,productReq]);if(!active)return;setCategorias(c.data);if(p)setForm({name:p.data.name||'',brand:p.data.brand||'',categoryId:String(p.data.categoryId),price:String(p.data.price),stock:String(p.data.stock),image:p.data.image||'',description:p.data.description||'',featured:Boolean(p.data.featured)});}catch(error){if(active)setErro(error.response?.data?.message||'Não foi possível carregar os dados do produto.')}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[editando,id]);
  function change(e){const{name,value,type,checked}=e.target;setForm((f)=>({...f,[name]:type==='checkbox'?checked:value}))}
  async function submit(e){e.preventDefault();setErro('');setSucesso('');if(!form.name.trim()||!form.categoryId||Number(form.price)<0||!Number.isInteger(Number(form.stock))||Number(form.stock)<0){setErro('Preencha nome, categoria, preço e estoque corretamente.');return;}const payload={name:form.name.trim(),brand:form.brand.trim()||null,categoryId:Number(form.categoryId),price:Number(form.price),stock:Number(form.stock),image:form.image.trim()||null,description:form.description.trim()||null,featured:form.featured};try{setSaving(true);if(editando)await api.put(`/products/${id}`,payload);else await api.post('/products',payload);setSucesso(editando?'Produto atualizado com sucesso.':'Produto cadastrado com sucesso.');setTimeout(()=>navigate('/admin/produtos'),500);}catch(error){setErro(error.response?.data?.message||'Não foi possível salvar o produto.')}finally{setSaving(false)}}
  if(loading)return <LoadingAdmin text="Carregando produto..."/>;
  return <div className="max-w-4xl"><Link to="/admin/produtos" className="mb-5 inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-lime-300"><ArrowLeft size={16}/> Voltar para produtos</Link><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Catálogo</p><h1 className="mt-1 text-3xl font-black">{editando?'Editar produto':'Novo produto'}</h1></div><ErrorBox message={erro}/><SuccessBox message={sucesso}/>
    <form onSubmit={submit} className="space-y-5 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-[1fr_220px]"><Field label="Nome"><input className="admin-input" name="name" value={form.name} onChange={change} required/></Field><Field label="Marca"><input className="admin-input" name="brand" value={form.brand} onChange={change} placeholder="Ex.: Logitech"/></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Categoria"><select className="admin-input" name="categoryId" value={form.categoryId} onChange={change} required><option value="">Selecione</option>{categorias.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Preço (R$)"><input className="admin-input" type="number" min="0" step="0.01" name="price" value={form.price} onChange={change} required/></Field><Field label="Estoque"><input className="admin-input" type="number" min="0" step="1" name="stock" value={form.stock} onChange={change} required/></Field></div><Field label="URL da imagem"><input className="admin-input" type="url" name="image" value={form.image} onChange={change} placeholder="https://..."/><SerperImagePicker productName={form.name} brand={form.brand} onSelect={(url)=>setForm((current)=>({...current,image:url}))}/></Field><Field label="Descrição"><textarea className="admin-input min-h-36 resize-y" name="description" value={form.description} onChange={change}/></Field><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-950/50 p-4"><input type="checkbox" name="featured" checked={form.featured} onChange={change} className="h-4 w-4 accent-lime-400"/><Star size={17} className={form.featured?'text-lime-300':'text-zinc-600'}/><div><p className="text-sm font-semibold">Produto em destaque</p><p className="text-xs text-zinc-600">Prioriza o item na vitrine da loja.</p></div></label>{form.image&&<div><p className="mb-2 text-xs text-zinc-600">Prévia</p><img src={form.image} alt="Prévia" className="h-44 max-w-full rounded-xl bg-white object-contain p-2"/></div>}<div className="flex justify-end gap-3 border-t border-zinc-800 pt-5"><button type="button" onClick={()=>navigate('/admin/produtos')} className="rounded-xl border border-zinc-800 px-4 py-2.5 text-sm">Cancelar</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-lime-400 px-5 py-2.5 text-sm font-black text-zinc-950 disabled:opacity-50"><Save size={16}/>{saving?'Salvando...':'Salvar produto'}</button></div></form>
  </div>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm text-zinc-400">{label}</span>{children}</label>}
export default CadastroProduto;
