import { UserPlus } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

function Cadastro() {
  const { cadastrar }=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({nome:'',email:'',telefone:'',senha:'',confirmarSenha:''}); const [erro,setErro]=useState(''); const [carregando,setCarregando]=useState(false);
  const change=(campo)=>(e)=>setForm((prev)=>({...prev,[campo]:e.target.value}));
  function validar(){if(form.nome.trim().length<2)return'Informe seu nome.';if(!/^\S+@\S+\.\S+$/.test(form.email))return'E-mail inválido.';if(form.senha.length<8)return'A senha deve ter pelo menos 8 caracteres.';if(form.senha!==form.confirmarSenha)return'As senhas não coincidem.';return'';}
  async function submit(e){e.preventDefault();const msg=validar();if(msg){setErro(msg);return;}try{setCarregando(true);setErro('');await cadastrar({nome:form.nome,email:form.email,senha:form.senha,telefone:form.telefone});navigate('/');}catch(error){setErro(error.message);}finally{setCarregando(false)}}
  return <main className="min-h-[calc(100vh-74px)] bg-zinc-950 px-4 py-10 text-white"><div className="mx-auto max-w-2xl"><div className="mb-6 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Nova conta</p><h1 className="mt-1 text-3xl font-black">Entre para a TechGarage</h1><p className="mt-2 text-sm text-zinc-500">Carrinho persistente, checkout e histórico de pedidos em uma única conta.</p></div><form onSubmit={submit} className="rounded-3xl border border-zinc-800 bg-zinc-900/60 p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo"><input value={form.nome} onChange={change('nome')} className="store-input" autoComplete="name"/></Field><Field label="Telefone"><input value={form.telefone} onChange={change('telefone')} className="store-input" placeholder="(41) 99999-9999" autoComplete="tel"/></Field></div><div className="mt-4"><Field label="E-mail"><input type="email" value={form.email} onChange={change('email')} className="store-input" autoComplete="email"/></Field></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Senha"><input type="password" value={form.senha} onChange={change('senha')} className="store-input" autoComplete="new-password"/></Field><Field label="Confirmar senha"><input type="password" value={form.confirmarSenha} onChange={change('confirmarSenha')} className="store-input" autoComplete="new-password"/></Field></div><p className="mt-2 text-xs text-zinc-600">Use pelo menos 8 caracteres.</p>{erro&&<p className="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{erro}</p>}<button disabled={carregando} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-lime-400 py-3 text-sm font-black text-zinc-950 hover:bg-lime-300 disabled:opacity-50"><UserPlus size={17}/>{carregando?'Criando conta...':'Criar minha conta'}</button><p className="mt-5 text-center text-sm text-zinc-500">Já possui cadastro? <Link to="/login" className="font-semibold text-lime-300">Entrar</Link></p></form></div></main>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-zinc-400">{label}</span>{children}</label>}
export default Cadastro;
