import { LogIn, ShieldCheck, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [erro,setErro]=useState(''); const [carregando,setCarregando]=useState(false);
  async function submit(e){e.preventDefault();setErro('');if(!email||!senha){setErro('Preencha e-mail e senha.');return;}try{setCarregando(true);const user=await login(email,senha);const fallback=user.role==='ADMIN'&&location.state?.from?.startsWith('/admin')?'/admin':'/';navigate(location.state?.from||fallback,{replace:true});}catch(error){setErro(error.message);}finally{setCarregando(false)}}
  return <main className="min-h-[calc(100vh-74px)] bg-zinc-950 px-4 py-12 text-white"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-900/60 shadow-2xl lg:grid-cols-[.9fr_1.1fr]"><section className="hidden border-r border-zinc-800 bg-[radial-gradient(circle_at_20%_20%,rgba(163,230,53,.18),transparent_38%),#0f0f12] p-10 lg:flex lg:flex-col lg:justify-between"><div><p className="text-xl font-black">Tech<span className="text-lime-300">Garage</span></p><h2 className="mt-16 text-4xl font-black leading-tight">Sua conta, seus pedidos, seu setup.</h2><p className="mt-4 text-sm leading-6 text-zinc-500">Acesse para sincronizar carrinho, acompanhar compras e gerenciar seus dados.</p></div><div className="space-y-3"><Benefit icon={ShieldCheck} text="Sessão protegida por cookie HttpOnly"/><Benefit icon={Zap} text="Checkout e estoque sincronizados em tempo real"/></div></section><section className="p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Acesso</p><h1 className="mt-1 text-3xl font-black">Entrar</h1><p className="mt-2 text-sm text-zinc-500">Use sua conta TechGarage para continuar.</p><form onSubmit={submit} className="mt-7 space-y-4"><Field label="E-mail"><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="store-input" placeholder="seu@email.com" autoComplete="email"/></Field><Field label="Senha"><input type="password" value={senha} onChange={(e)=>setSenha(e.target.value)} className="store-input" placeholder="••••••••" autoComplete="current-password"/></Field>{erro&&<p className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{erro}</p>}<button disabled={carregando} className="flex w-full items-center justify-center gap-2 rounded-xl bg-lime-400 py-3 text-sm font-black text-zinc-950 hover:bg-lime-300 disabled:opacity-50"><LogIn size={17}/>{carregando?'Entrando...':'Entrar na TechGarage'}</button></form><p className="mt-6 text-center text-sm text-zinc-500">Ainda não tem conta? <Link to="/cadastro" className="font-semibold text-lime-300 hover:text-lime-200">Criar conta</Link></p></section></div></main>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-zinc-400">{label}</span>{children}</label>}
function Benefit({icon:Icon,text}){return <div className="flex items-center gap-3 text-xs text-zinc-400"><div className="grid h-8 w-8 place-items-center rounded-lg bg-lime-400/10 text-lime-300"><Icon size={15}/></div>{text}</div>}
export default Login;
